global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#konstantin_ermakov'
