version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${UI_SERVICE_PORT}:9292/tcp
    networks:
      - frontend
    logging:
      driver: "fluentd"
      options:
      fluentd-address: localhost:24224
      tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  post:
    image: ${USER_NAME}/post:${POST_SERVICE_VERSION}
    networks:
    - backend
    - frontend
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
    - post_db
    ports:
    - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${COMMENT_SERVICE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.100.0/24
  frontend:
    ipam:
      config:
        - subnet: 192.168.10.0/24
