version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.4.0
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.4.0
    ports:
      - "5601:5601"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - backend
      - frontend

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.100.0/24
  frontend:
    ipam:
      config:
        - subnet: 192.168.10.0/24
