kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: FPKtr+rz3dlYefDSxftieH7ZgXGBAaHCdxQcGGQZBxQ=
      - identity: {}
